name: photon
version: '2.0.0+8'
publish_to: none
environment: 
  sdk: '>=3.5.2 <=4.0.0'
description: A new Flutter project.
dependencies: 
  ai_barcode_scanner: '^5.2.1'
  animated_splash_screen: any
  cupertino_icons: '^1.0.6'
  device_apps: 
    git: 'https://github.com/sumitsharansatsangi/flutter_plugin_device_apps.git'
  dio: '^5.4.2+1'
  file_picker: any
  flex_color_scheme: any
  flutter: 
    sdk: flutter
  flutter_displaymode: '^0.6.0'
  flutter_markdown: any
  flutter_svg: '^2.0.10+1'
  graphic: '^2.2.1'
  hive: '^4.0.0-dev.2'
  introduction_screen: '^3.1.14'
  isar_flutter_libs: '^4.0.0-dev.14'
  lottie: any
  mailto: '^2.0.0'
  modal_bottom_sheet: '^3.0.0'
  open_filex: '^4.5.0'
  page_transition: any
  path: '^1.9.0'
  path_provider:
    git: 'https://github.com/kumsumit/path_provider.git'
  permission_handler:
    git: 'https://github.com/kumsumit/permission_handler.git'
  qr_flutter:  
  receive_sharing_intent: 
    git: 'https://github.com/sumitsharansatsangi/receive_sharing_intent.git'
  refreshed: '^2.9.0'
  stop_watch_timer: any
  system_settings: 
    git: 'https://github.com/sumitsharansatsangi/system_settings.git'
  unicons: '^3.0.0'
  url_launcher:
    git: 'https://github.com/kumsumit/url_launcher.git'
dev_dependencies: 
  build_runner: any
  change_app_package_name: any
  flutter_distributor: any
  flutter_lints: '^4.0.0'
  flutter_test: 
    sdk: flutter
  # msix: '^3.16.8'
  pubspec_dependency_sorter: '^1.0.4'

dependency_overrides:
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

msix_config: 
  display_name: Photon
  publisher_display_name: N/A
  identity_name: com.kumpali.photon
  msix_version: 1.1.1.0
  logo_path: 'assets\images\icon.png'
  capabilities: 'internetClient, internetServer'
  certificate_path: thekeystore.pfx
  certificate_password: null
flutter: 
  uses-material-design: true
  assets: 
    - assets/icons/
    - assets/lottie/
    - assets/images/
    - assets/texts/
    - assets/avatars/
  fonts: 
    - family: ytf
      fonts: 
        - asset: assets/fonts/Yftoow-R.ttf
    - family: questrial
      fonts: 
        - asset: assets/fonts/Questrial-Regular.ttf
