name: photon
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+8

environment:
  sdk: ">=3.5.0 <=4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  lottie:
  unicons:
  dio: ^5.1.1
  path_provider: ^2.0.11
  get_it: ^8.0.0
  get:
  path: ^1.8.1
  animated_splash_screen:
  flex_color_scheme:
  url_launcher: ^6.1.5
  page_transition:
  introduction_screen: ^3.1.14
  mailto: ^2.0.0
  receive_sharing_intent: ^1.8.0
  modal_bottom_sheet:
  flutter_displaymode: ^0.6.0
  adaptive_theme:
  stop_watch_timer:
  flutter_markdown:
  device_apps:
    git: https://github.com/sumitsharansatsangi/flutter_plugin_device_apps.git
  http:
  provider:
  mobile_scanner:
    git: https://github.com/sumitsharansatsangi/mobile_scanner.git
  file_picker:
  open_file: ^3.5.10
  permission_handler: ^11.1.0
  qr_flutter: ^4.0.0
  graphic: ^2.2.1
  saf_util: ^0.6.2
  saf_stream: ^0.11.1
  open_settings_plus: ^0.4.0
  bonsoir: ^5.1.11
  pointycastle: ^3.9.1
  basic_utils:
  convert:
  uuid:
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  # flutter_distributor: ^0.4.5
  build_runner:
  change_app_package_name:
  # msix: ^3.16.8

dependency_overrides:
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
msix_config:
  display_name: Photon
  publisher_display_name: N/A
  identity_name: dev.abhi.photon
  msix_version: 1.1.1.0
  logo_path: assets\images\icon.png
  capabilities: internetClient, internetServer
  certificate_path: thekeystore.pfx
  certificate_password:
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/icons/
    - assets/lottie/
    - assets/images/
    - assets/texts/
    - assets/avatars/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: ytf
      fonts:
        - asset: assets/fonts/Yftoow-R.ttf
    - family: questrial
      fonts:
        - asset: assets/fonts/Questrial-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
